version: 0.2

phases:
  pre-build:
    commands:
      - echo Entered prebuild phase
  build:
    commands:
      - echo Build again started on 
      - mvn -DskipTests clean package  
  post_build:
    commands:
      - echo Build completed
  artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes